### ISSUE TITLE
leaflet:::getMapData

### ISSUE THREAD

**Issue by tim-salabim** [bhaskarvk/leaflet#14]
Could you please make sure that for the next release of leaflet you export getMapData. When I run R CMD check on mapview I get:

* checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: ‘leaflet:::getMapData’
  See the note in ?`:::` about the use of this operator.

I think I can convince CRAN for now that this is needed, yet it would be great to not have to argue about this in the future.

Cheers
Tim

**Comment by bhaskarvk** [comment]
Thoughts @jcheng5 ?

**Comment by jcheng5** [comment]
Yeah, I don't have a problem with that...

**Comment by bhaskarvk** [comment]
Fixed in feature/upgrade-leaflet.
