### ISSUE TITLE
addSimpleGraticule

### ISSUE THREAD

**Issue by einarhjorleifsson** [bhaskarvk/leaflet#5]
is it possible within leaflet.js to have different interval for long and lat?

thinking then of something within the r-leaflet:

```
addSimpleGraticule(interval=c(20,40))
```
einar

**Comment by bhaskarvk** [comment]
Yes see the arguments to the function call.

**Comment by bhaskarvk** [comment]
@einarhjorleifsson Sorry I misunderstood the question earlier. The underlying plugin doesn't support what you ask. You should probably create this BR on the original plugin repo https://github.com/turban/Leaflet.Graticule
